#ifndef CONFIG_H
#define CONFIG_H

#define SHELL_MAX_INPUT_SIZE 1024
#define SHELL_MAX_ERROR_SIZE 512
#define SHELL_MAX_TOKEN_STRING_SIZE 50
#define SHELL_MAX_NODE_STRING_SIZE 512
#define SHELL_MAX_TOKENS 1024

#endif