#ifndef CONFIG_H
#define CONFIG_H

#define CALC_MAX_INPUT_SIZE 1024
#define CALC_MAX_ERROR_SIZE 512
#define CALC_MAX_TOKEN_STRING_SIZE 50
#define CALC_MAX_NODE_STRING_SIZE 512
#define CALC_MAX_TOKENS 1024

#endif