#ifndef ISR80H_H
#define ISR80H_H

#include <hardware/idt.h>
#include <syscall/misc.h>
#include <syscall/io.h>
#include <syscall/heap.h>
#include <syscall/graphics.h>
#include <syscall/file.h>

enum SystemCommands
{
    SYSTEM_COMMAND0_SUM,
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_GETKEY,
    SYSTEM_COMMAND3_PUTCHAR,
    SYSTEM_COMMAND4_MALLOC,
    SYSTEM_COMMAND5_FREE,
    SYSTEM_COMMAND6_PROCESS_LOAD,
    SYSTEM_COMMAND7_INVOKE_SYSTEM_COMMAND,
    SYSTEM_COMMAND8_GET_PROGRAM_ARGUMENTS,
    SYSTEM_COMMAND9_EXIT,
    SYSTEM_COMMAND10_FREE_ALL,
    SYSTEM_COMMAND11_GET_ENVIRON_VAR,
    SYSTEM_COMMAND12_SET_ENVIRON_VAR,
    SYSTEM_COMMAND13_PUT_PIXEL,
    SYSTEM_COMMAND14_FOPEN,
    SYSTEM_COMMAND15_FSEEK,
    SYSTEM_COMMAND16_FREAD,
    SYSTEM_COMMAND17_FWRITE,
    SYSTEM_COMMAND18_FSTAT,
    SYSTEM_COMMAND19_FCLOSE,
    SYSTEM_COMMAND20_START_IPC,
    SYSTEM_COMMAND21_POP_IPC,
};

void isr80h_register_commands();

#endif